package com.example.main1;

import java.util.ArrayList;
import java.util.Arrays;

public class Words_Set {
    public static ArrayList<String> words = new ArrayList<String>(Arrays.asList(
            "allow", "ancient", "bear", "cause", "company", "concern", "consider", "draw", "environment", "face", "fire", "genetic", "government", "individual", "likely", "lose", "matter", "mean", "patient", "plant", "positive", "present", "provide", "race", "raise", "realize", "reason", "state", "still", "subject", "add", "affect", "amount", "arm", "article", "creative", "deal", "education", "eventually", "fine", "influence", "involve", "material", "negative", "normal", "notice", "object", "planet", "prevent", "process",
            "purpose", "relax", "require", "research", "respect", "rest", "support", "suppose", "unique", "various", "accept", "achieve", "advance", "attitude", "avoid", "benefit", "besides", "career", "challenge", "cure", "describe", "detail", "essential", "generation", "industry", "issue", "limit", "male/", "female", "opportunity", "particular", "population", "reality", "recent", "reduce", "remain", "similar", "suggest", "tear", "tiny", "treat", "active", "appearance", "approach", "available", "beat", "belong", "calm", "character", "contain",
            "depend", "disabled", "encourage", "expert", "figure", "instance", "match", "merely", "method", "movement", "occur", "perform", "polite", "quality", "reflect", "resource", "separate", "species", "stick", "suffer", "variety", "account", "adventure", "advertise", "aspect", "aware", "block", "commercial", "compare", "complex", "crime", "damage", "demand", "determine", "establish", "feed", "fit", "freedom", "lie", "lower", "ordinary", "otherwise", "range", "recognize", "responsible", "satisfy", "solution", "spread", "supply", "survive",
            "tradition", "advantage", "apply", "appreciate", "attack", "attempt", "board", "chat", "content", "direct", "due", "effective", "entire", "equipment", "exchange", "exist", "familiar", "folk", "fuel", "gain", "gather", "hide", "manage", "medium", "nevertheless", "refer", "replace", "soil", "term", "trick", "youth", "apart", "belief", "court", "decrease", "discovery", "discuss", "economy", "emotion", "escape", "ignore", "mass", "measure", "organism", "pollute", "predict", "prefer", "pressure", "private", "progress",
            "proper", "rate", "relate", "risk", "seek", "senior", "specific", "succeed", "suit", "valuable", "willing", "advise", "argue", "attend", "capital", "confident", "credit", "crisis", "custom", "enemy", "grain", "handle", "humanity", "introduction", "mention", "moral", "organize", "origin", "pleasant", "possibility", "potential", "preserve", "remind", "respond", "sickness", "solar", "somehow", "strategy", "surface", "trust", "typical", "approximately", "award", "battle", "behave", "brief", "complain", "connect", "current", "desire",
            "disappoint", "discipline", "efficient", "element", "entertainment", "export", "failure", "feature", "freeze", "imagination", "incredible", "lack", "mental", "mine", "observe", "overcome", "participate", "publish", "regret", "sort", "worth", "access", "alarm", "attract", "automobile", "climate", "compete", "confuse", "constant", "contribute", "enable", "enormous", "ethical", "factor", "function", "insect", "intelligence", "labor", "maintain", "principle", "protection", "prove", "realistic", "refuse", "regardless", "region", "remove", "rough", "struggle", "theory",
            "virtual", "accurate", "author", "bother", "broadcast", "client", "curious", "disaster", "embarrass", "flat", "identify", "impact", "impress", "inclined", "injure", "instrument", "link", "muscle", "mystery", "novel", "opposite", "popularity", "praise", "rude", "sculpture", "shy", "somewhat", "spot", "steal", "surround", "victim", "ancestor", "barely", "bury", "celebrate", "characteristic", "conduct", "contrast", "convenient", "endanger", "frequent", "independent", "indicate", "insist", "intend", "locate", "mankind", "mission", "narrow", "release",
            "rescue", "reward", "row", "section", "significant", "stretch", "survey", "tongue", "tough", "vocabulary", "wound", "addict", "agenda", "artistic", "concept", "consist", "consume", "convince", "disagree", "explanation", "explore", "fund", "furthermore", "helpless", "military", "novel", "nuclear", "passage", "patience", "personality", "persuade", "promote", "recommend", "revolution", "scale", "soul", "spiritual", "stare", "tropical", "weapon", "witness", "aim", "analyze", "announce", "aside", "atmosphere", "basis", "charge", "comment", "critical",
            "debate", "decade", "defeat", "delight", "edge", "extend", "frighten", "hire", "indifferent", "insurance", "obtain", "plain", "rely", "represent", "request", "strike", "suitable", "therapy", "unexpected", "vast", "vehicle", "aid", "appointment", "appropriate", "astronaut", "bound", "charity", "chief", "code", "deliver", "expose", "fascinate", "firm", "frustrate", "genius", "harm", "heal", "lecture", "memorize", "practice", "precious", "prejudice", "prison", "react", "recover", "seldom", "series", "terrific", "track", "transfer",
            "vary", "adapt", "arrange", "blame", "claim", "combine", "conclusion", "contrary", "disturb", "exact", "excitement", "grab", "harvest", "ideal", "identity", "laboratory", "likewise", "miracle", "motion", "nominate", "phrase", "physics", "puzzle", "rare", "reveal", "review", "smooth", "substance", "threat", "useless", "vote", "accordingly", "admit", "amaze", "attach", "comfort", "depressed", "destruction", "discourage", "duty", "expectation", "fantasy", "formal", "former", "high-tech", "improvement", "legal", "leisure", "literature", "manufacture",
            "misunderstand", "policy", "poverty", "privacy", "reasonable", "regard", "relieve", "routine", "select", "swing", "tremendous", "afford", "anger", "annoy", "aptitude", "artificial", "bend", "bless", "carbon", "dioxide", "civil", "column", "companion", "conflict", "destination", "distant", "insure", "invade", "lean", "means", "ordinary", "poison", "profit", "religion", "rent", "seemingly", "shelter", "statue", "steady", "thrill", "vital", "wander", "apologize", "appeal", "awake", "construct", "crash", "delay", "dust", "explosion",
            "expressive", "extreme", "facility", "freshman", "guard", "incident", "layer", "make-up", "marine", "motivate", "operate", "overnight", "oxygen", "pace", "peninsular", "photography", "purchase", "qualify", "remote", "representative", "sacrifice", "ultimate", "alternative", "assignment", "bomb", "broad", "capture", "clue", "conductor", "cruel", "declare", "devote", "display", "evil", "faith", "fault", "float", "glance", "horizon", "hunger", "include", "institute", "interact", "primary", "reserve", "rid", "summit", "trend", "undoubtedly", "usual",
            "weigh", "wildlife", "agriculture", "anxious", "arrow", "ashamed", "civilization", "commit", "context", "defend", "deserve", "device", "examine", "expand", "gravity", "habitat", "highway", "horn", "mixture", "obey", "owe", "palm", "protest", "rapid", "readily", "rural", "scholar", "secure", "sink", "swallow", "thoughtful", "transform", "absorb", "authority", "blank", "collapse", "contemporary", "crawl", "criticize", "differ", "drown", "elderly", "exhibit", "fare", "gloomy", "grant", "guarantee", "infant", "inner", "judgement",
            "namely", "panic", "pole", "propose", "quantity", "raft", "seal", "severe", "statement", "sum", "tension", "trail", "abruptly", "admire", "anxiety", "awful", "bar", "belonging", "biology", "chew", "concentrate", "ease", "estimate", "evidence", "famine", "fellow", "fossil", "generous", "instant", "lay", "pour", "previous", "semester", "settle", "shame", "shoot", "suicide", "translate", "transport", "visual", "wealthy", "yell", "aloud", "association", "border", "brilliant", "chore", "define", "donate", "dump",
            "encounter", "evolve", "globe", "intention", "interrupt", "journal", "luxurious", "majority", "neglect", "organic", "permanent", "precise", "procedure", "pursue", "relative", "royal", "shadow", "shortage", "string", "submit", "sweep", "violence", "adopt", "ambassador", "assume", "category", "chase", "circumstance", "classic", "conserve", "cycle", "delicate", "deposit", "desperate", "dirt", "dramatic", "election", "emphasize", "equality", "extinction", "festive", "forgive", "income", "inform", "possess", "pretend", "property", "remark", "ruin", "scarcely",
            "strict", "sufficient", "acquire", "alike", "awaken", "careless", "conscious", "employ", "exhaust", "forbid", "found", "grand", "junk", "occupy", "oppose", "orbit", "organ", "permit", "preparation", "priest", "ridiculous", "ritual", "solid", "stare", "sword", "telescope", "theme", "tone", "tourism", "tragic", "welfare", "whistle", "arrest", "channel", "clay", "command", "conference", "crew", "disorder", "emission", "era", "executive", "expense", "fashionable", "fortunate", "household", "identical", "leap", "objective", "passionate",
            "passive", "pose", "pray", "primitive", "punish", "quit", "remarkable", "simmarize", "slap", "statistics", "toss", "weaken", "accomplish", "accustomed", "adjust", "agency", "annual", "ash", "bold", "bush", "calculate", "capacity", "cast", "considerable", "continuous", "dislike", "distinguish", "document", "eliminate", "ethnic", "grave", "guilty", "illustrate", "import", "iron", "isolate", "modify", "occasion", "stuff", "tax", "trial", "venture", "cheerful", "classify", "deny", "depict", "drag", "dye", "endure", "engage",
            "enhance", "fulfill", "historic", "myth", "overweight", "philosophy", "pile", "pottery", "remains", "resort", "rob", "sensitive", "shade", "sour", "stock", "surgery", "trap", "turn", "union", "vacuum", "verbal", "visible", "assist", "bitter", "clap", "corporation", "coverage", "craft", "creation", "despair", "ethic", "filter", "infect", "ingredient", "insight", "instinct", "landscape", "liquid", "lively", "mechanical", "merit", "miserable", "promising", "scold", "sensible", "skip", "stir", "strengthen", "supreme", "terrify",
            "tug", "weave", "abuse", "alley", "arrival", "bargain", "beard", "boundary", "carbohydrate", "colony", "committee", "complicated", "consequence", "considerate", "continual", "descendent", "diverse", "enthusiastic", "entrance", "fortune", "inspire", "install", "intensive", "literary", "punch", "pupil", "resist", "roar", "rub", "specialize", "split", "starve", "abstract", "actual", "ban", "capable", "confirm", "creep", "daydream", "depart", "diligent", "drift", "eager", "emerge", "enrich", "forecast", "harsh", "herd", "pale", "pastime",
            "politics", "prospect", "psychology", "register", "resident", "strain", "stroke", "trait", "veterinarian", "volume", "wagon", "wilderness", "accompany", "adjourn", "assembly", "burst", "decorate", "farewell", "flash", "funeral", "germ", "hardship", "launch", "legend", "masterpiece", "millionaire", "minister", "murder", "obstacle", "opinion", "particle", "pause", "sorrowful", "spin", "superior", "swift", "tide", "unite", "urban", "valid", "vivid", "weird", "breakdown", "chemistry", "comet", "cooper", "council", "counsel", "deed", "dimension",
            "district", "drawer", "ecosystem", "fame", "flame", "initial", "jealous", "occasional", "optimistic", "prior", "prone", "reject", "sincere", "smash", "spacecraft", "spoil", "strive", "tempt", "tolerate", "uncover", "undergo", "urge", "avenue", "barrier", "basin", "dynasty", "exotic", "extraordinary", "fasten", "fee", "fertile", "fusion", "genuine", "graceful", "gym", "halfway", "humble", "lessen", "monster", "overlook", "overwhelm", "peel", "proceed", "resemble", "resume", "scratch", "triangle", "trigger", "volcano", "vow",
            "warehouse", "workforce", "atomic", "automatic", "bare", "concrete", "conventional", "dynamic", "embrace", "eternal", "fade", "harness", "hatch", "hook", "imitate", "imply", "interfere", "investigate", "plot", "privilege", "rank", "reunification", "rival", "scholarship", "session", "sponsor", "stem", "storage", "surgeon", "sympathy", "territory", "thirst", "abandon", "absolute", "alien", "approve", "arise", "boast", "congratulate", "consult", "dare", "dedicate", "diagnose", "intellectual", "loose", "meantime", "mercy", "millennium", "moisture", "monument",
            "motorcycle", "mummy", "nerve", "nightmare", "nun", "nutrition", "outcome", "paradise", "pioneer", "pure", "raw", "selfish", "abandon", "absolute", "alien", "approve", "boast", "compose", "congratulate", "consult", "dare", "dedicate", "diagnose", "elect", "intellectual", "loose", "nod", "prime", "pure", "raw", "selfish", "spare", "spectacular", "steep", "subjective", "tickle", "trace", "voluntary", "wipe", "worship", "worthwhile", "wreck", "cone", "criminal", "cube", "decline", "diameter", "drought", "empire", "encyclopedia",
            "evolution", "excursion", "fate", "feather", "feedback", "fermentation", "minimum", "mutural", "noble", "outgoing", "outstanding", "overall", "partial", "pronounce", "restrict", "retire", "scatter", "sting", "strip", "suck", "suspect", "symbolize", "administration", "adolescent", "archaeologist", "architecture", "assumption", "attoney", "burden", "cabin", "caterpillar", "cereal", "cliff", "democracy", "domestic", "gigantic", "grateful", "infinite", "innocent", "latter", "loyal", "mislead", "mud", "paralyze", "pat", "polish", "prohibit", "recite", "renew", "shatter",
            "sleeve", "sow", "breeze", "costly", "countless", "courageous", "crucial", "cruise", "crush", "deadly", "dense", "digest", "dim", "disguise", "distort", "exclaim", "flavor", "grin", "honesty", "impose", "interpret", "kindergarten", "scenery", "signature", "slope", "sophomore", "spokesperson", "temper", "thrift", "transaction", "tribe", "wetland", "ache", "alter", "chant", "cheat", "choke", "chop", "competent", "conquer", "crack", "dull", "dumb", "faint", "freelancer", "jaw", "lottery", "nap", "necessity", "prey",
            "productivity", "rainfall", "ranch", "refund", "route", "salvation", "sequence", "sermon", "spill", "temporary", "urgent", "vague", "fold", "frost", "galaxy", "glacier", "greed", "grief", "guidance", "headline", "loan", "lyric", "midst", "minority", "molecule", "pedestrian", "physician", "slim", "soak", "sociable", "spacious", "sparkle", "spit", "stain", "startle", "stiff", "stimulate", "striking", "stubborn", "stun", "subtle", "tumble", "detergent", "dignity", "drill", "editorial", "elbow", "embryo", "exception", "expedition",
            "feast", "fetus", "fiber", "finance", "flesh", "leak", "massive", "mature", "memorial", "naked", "numerous", "portion", "prominent", "recall", "reproduce", "resolve", "scoop", "screw", "scrub", "seize", "slam", "slight", "admission", "affection", "aircraft", "bay", "biotechnology", "budget", "closet", "colleague", "compliment", "courtesy", "defect", "demonstrate", "dismiss", "distribute", "erupt", "foul", "frank", "gradual", "horrible", "immediate", "insult", "internal", "invest", "magnificent", "nurture", "overflow", "perceive", "proof",
            "viewpoint", "voyage", "accountant", "aggression", "appliance", "autograph", "beam", "canal", "cathedral", "ceiling", "celebrity", "charm", "criticism", "edible", "envious", "excel", "extensive", "faraway", "fatal", "fearful", "flatter", "fluent", "grind", "halt", "hesitate", "highlight", "hinder", "hop", "improvise", "irritate", "profession", "subscription", "accuse", "adequate", "alert", "cemetery", "collide", "commerce", "contaminate", "controversial", "deliberate", "desirable", "detect", "dictate", "doom", "drain", "evaluate", "glow", "intersection", "lumber",
            "mammal", "principal", "republic", "spice", "suburb", "superficial", "telecommunication", "tuition", "usage", "warrior", "wrinkle", "yearbook", "allowance", "altitude", "apparent", "breed", "bump", "carve", "cease", "cherish", "depression", "deprive", "designate", "duplicate", "journalist", "personnel", "phenomenon", "pulse", "reconciliation", "sensation", "sewage", "shield", "snap", "solitary", "spark", "spear", "terminal", "trivial", "undone", "vain", "vertical", "vocal", "await", "blend", "cancel", "corps", "correspond", "dawn", "immigration", "jail",
            "lap", "litter", "liver", "messy", "microscope", "monastery", "monotonous", "nonsense", "outlet", "parental", "peculiar", "perimeter", "perspective", "plume", "profound", "random", "scream", "shallow", "shrug", "sigh", "windshield", "worsen", "anniversary", "anticipate", "bullet", "candidate", "congestion", "dismay", "division", "equator", "errand", "extent", "faucet", "gender", "hell", "inclined", "literal", "marvelous", "modest", "neutral", "noticeable", "ongoing", "priceless", "squeeze", "stumble", "substitute", "supervise", "tilt", "transmit", "transplant",
            "violate", "weep", "barn", "blossom", "conscience", "consensus", "constitution", "contract", "cosmos", "counterpart", "debris", "destiny", "dialect", "disgrace", "fundamental", "furious", "gospel", "immune", "intent", "intimate", "juvenile", "kneel", "linguistic", "mural", "offend", "refine", "reform", "restore", "reverse", "shift", "shrink", "soar", "advert", "ankle", "artifact", "asset", "audition", "bias", "bud", "ceramic", "circulation", "compound", "core", "destined", "flexible", "fragile", "geometry", "habitual", "harmonious", "outlaw",
            "overhear", "perish", "pierce", "plunge", "pound", "prevail", "quote", "reap", "reception", "shave", "symptom", "workout", "absence", "affair", "ambition", "blueprint", "chilly", "distinct", "dizzy", "drastic", "exceed", "exclude", "fierce", "flourish", "foretell", "fountain", "grasp", "graze", "harbor", "inherit", "instruct", "justice", "meditation", "nourish", "originate", "refugee", "scent", "souvenir", "splash", "triumph", "wholesale", "wind", "absurd", "accessory", "arrogant", "beloved", "cooperate", "cunning", "currency", "damp"
    ));
}
